# Generated by Django 3.2 on 2022-10-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_stargazer_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stargazer_company',
            name='company',
            field=models.CharField(max_length=128),
        ),
    ]
