# Generated by Django 3.2 on 2022-10-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_issue_company_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='committer_company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=32)),
                ('company', models.CharField(max_length=128)),
                ('get_time', models.DateTimeField()),
            ],
        ),
    ]
