# Generated by Django 3.2 on 2022-11-01 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_allennlp_stargazer_company_allennlp_stargazer_company_statistic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='allennlp_stargazer_company',
            new_name='pandas_stargazer_company',
        ),
        migrations.RenameModel(
            old_name='allennlp_stargazer_company_statistic',
            new_name='pandas_stargazer_company_statistic',
        ),
    ]
