# Generated by Django 3.2 on 2022-11-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_pandas_committer_company_pandas_committer_company_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='pandas_total',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=128)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
