# Generated by Django 3.2 on 2022-11-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_pandas_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pandas_committer_company_statistic',
        ),
        migrations.DeleteModel(
            name='pandas_issue_company_statistic',
        ),
        migrations.DeleteModel(
            name='pandas_stargazer_company_statistic',
        ),
        migrations.AddField(
            model_name='committer_company_statistic',
            name='duplicate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='committer_company_statistic',
            name='flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue_company_statistic',
            name='duplicate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue_company_statistic',
            name='flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stargazer_company_statistic',
            name='duplicate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stargazer_company_statistic',
            name='flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
