# Generated by Django 3.2 on 2022-11-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20221120_1636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='committer_company_statistic',
        ),
        migrations.DeleteModel(
            name='issue_company_statistic',
        ),
        migrations.DeleteModel(
            name='stargazer_company_statistic',
        ),
    ]
