# Generated by Django 4.0.4 on 2022-12-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_committer_company_statistic_issue_company_statistic_stargazer_company_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='commit_by_day',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('comm_cnt', models.IntegerField(default=0)),
                ('desi_cnt', models.IntegerField(default=0)),
                ('modi_files', models.IntegerField(default=0)),
                ('modi_del', models.CharField(max_length=128)),
                ('modi_ins', models.CharField(max_length=128)),
                ('modi_files_core', models.IntegerField(default=0)),
                ('comm_cnt_core', models.IntegerField(default=0)),
                ('desi_cnt_core', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='commit_contributors',
            fields=[
                ('author', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('modi_files', models.IntegerField(default=0)),
                ('modi_del', models.IntegerField(default=0)),
                ('modi_ins', models.IntegerField(default=0)),
                ('if_core', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='commit_history',
            fields=[
                ('hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=128)),
                ('author_email', models.CharField(max_length=128)),
                ('committer', models.CharField(max_length=128)),
                ('committer_email', models.CharField(max_length=128)),
                ('time_local', models.DateTimeField(default=None)),
                ('commit_time', models.DateTimeField(default=None)),
                ('commit_intro', models.CharField(max_length=512)),
                ('commit_keyword', models.CharField(max_length=64)),
                ('if_design', models.BooleanField(default=False)),
                ('modi_files', models.IntegerField(default=0)),
                ('modi_del', models.IntegerField(default=0)),
                ('modi_ins', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='commit_update',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_update', models.DateTimeField(default=None)),
                ('time_last_record', models.DateTimeField(default=None)),
            ],
        ),
    ]
