# Generated by Django 3.2 on 2022-12-18 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20221218_1043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pytorch_issue',
            new_name='pytorch_issues',
        ),
    ]
