# Generated by Django 3.2 on 2022-12-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_pytorch_issue_pytorch_issues'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pytorch_issues',
        ),
    ]
