# Generated by Django 3.2 on 2022-12-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_pandas_issues'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pandas_issues',
        ),
        migrations.DeleteModel(
            name='pytorch_issues',
        ),
    ]
