# Generated by Django 3.2 on 2022-12-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20221218_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='pandas_issues',
            fields=[
                ('id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=None, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('closed_at', models.DateTimeField(default=None, null=True)),
                ('comment_cnt', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='pytorch_issues',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('closed_at', models.DateTimeField(default=None, null=True)),
                ('comment_cnt', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=512)),
            ],
        ),
    ]
