# Generated by Django 3.2 on 2022-12-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_pandas_issues_pytorch_issues'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pandas_issues',
        ),
    ]
